blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/v0idjs/toolbox-pro#readme
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/v0idjs/toolbox-pro/discussions
    about: Ask questions and discuss ideas
